### ISSUE TITLE
Stuck on "connecting..."

### ISSUE THREAD

**Issue by bnhovde** [chrisgillis/slackwolf#10]
I've got a pretty standard setup. MAMP pro/PHP 5.5.24 on OSX El Capitan.

Created blank bot and setup .env file with correct name/token.

Any ideas on how to debug this?

**Comment by bnhovde** [comment]
Strange! Just now after about 5 minutes the command ended with the following output:

Slackwolf\Game\Command\HelpCommand U02H8KBPX G0H3KT14Z
Slackwolf\Game\Command\StartCommand U02H8KBPX G0H3KT14Z

**Comment by chrisgillis** [comment]
It sounds like it did get a websocket but the event machine never executed the closure that echos 'Connected.' Probably a bug with the underlying slack client, but I pushed up some code to avoid squashing connection error messages that should help identify issues.

**Comment by marilyn** [comment]
I'm also on a standard Mac/PHP 5.5.29 setup, and seeing an unknown crash after about a minute, but with no output:

slackwolf (master)$ php bot.php 
Connecting...
slackwolf (master)$ php bot.php 
Connecting...
slackwolf (master)$ php bot.php 
Connecting...
slackwolf (master)$ cat .env 
BOT_TOKEN="xoxb-<bot hash>"
BOT_NAME="ye-olde-storyteller"
TIMEZONE="America/New_York"
slackwolf (master)$

Any ideas?

**Comment by marilyn** [comment]
It's actually just after ~20 seconds. I just generated a new token, and same thing. Looks like it's the $client->connect() in Slackwolf that's crashing, but not sure whether there's something else I can do to determine why.

**Comment by chrisgillis** [comment]
There is definitely a lot more debug code that could be added to the bot to help diagnose issues like yours a little better.

I checked out master, did a composer install, got a new realtime Api token, ran it and everything worked fine.

If you know any programming languages, you can install php storm and turn debug mode on, set a breakpoint at the top of bot.php and step through the code. It's pretty easy to grok! You should be able to see what exception is being thrown.
