### ISSUE TITLE
How does one deploy Slakwolf to heroku? 

### ISSUE THREAD

**Issue by joshentelect** [chrisgillis/slackwolf#14]
I can push the repo to heroku but can not get it running, any chance of a heroku deployment guide?

**Comment by chrisgillis** [comment]
I've never used heroku before but I'm guessing you'll want to go to the 'Post-deployment commands' section and add `php bot.php`

**Comment by joshentelect** [comment]
Sorted will do a branch with heroku config

**Comment by chrisgillis** [comment]
Looking forward to that, thanks!

**Comment by joshentelect** [comment]
https://github.com/joshentelect/heroku-Slackwolf
@chrisgillis You can merge it in
