### ISSUE TITLE
Kill command on IOS: channel not found

### ISSUE THREAD

**Issue by bboe** [chrisgillis/slackwolf#21]
![ios_slackwolf](https://cloud.githubusercontent.com/assets/48100/12041625/91edf51c-ae38-11e5-8372-1c1658fad608.jpeg)

It looks like the channel name wasn't detected when submitted via IOS. The same command worked once she went on slack via her computer.

**Comment by chrisgillis** [comment]
Interesting, thanks for the report. There must be something wrong with `ChannelIdFormatter`.  Which parses the channel name out of the message. Slack clients can send all kinds of stuff surrounding the actual channel name or id. This is the current code: `return trim($userId, '<>#\t\n\r\x0B');`
