### ISSUE TITLE
Seer shouldn't get info on Death

### ISSUE THREAD

**Issue by bboe** [chrisgillis/slackwolf#22]
It seems that the seer shouldn't have any information revealed to them until all the wolves have voted. Otherwise, the seer is able to leak information even if they are killed in the night.

**Comment by chrisgillis** [comment]
To speed up the game the night phase action gathering is simultaneous and then resolved all at once. No-one should be speaking during the night, anyways, it's against the spirit of the game, the same as they shouldn't be speaking after they're dead.

Slack doesn't really provide any facilities to support enforcing any of this.

**Comment by bboe** [comment]
I agree no one should be speaking during the night. Nevertheless, it seems it should be fairly trivial for the bot to wait to respond to the seer until only after the wolves have voted. It doesn't seem that would slow the progression of the game at all.

**Comment by chrisgillis** [comment]
In a normal game of Werewolf, the seer will still get to see even if they're killed during the night. Roles that offer protection like Bodyguard could potentially save the Seer even though they are killed, so the Seer should still have the opportunity to See.

**Comment by bboe** [comment]
Yes, if the seer stays alive they should be able to see. I feel like that should happen right before night ends as the last step though. While it happens in an offline game, there's no reason to give them information if they cannot/should not act on it.

**Comment by chrisgillis** [comment]
I still stand by my decision of simultaneous night actions. I've found it slows down the game too much waiting on werewolves,seer,bodyguard to sequentially enter their commands each night. 

Feel free to add a `.env` option that can toggle this on or off though, I think the configurability is a good idea.
