### ISSUE TITLE
Restart required when new person joins channel

### ISSUE THREAD

**Issue by bboe** [chrisgillis/slackwolf#24]
When we type `!start @player1 @player2 @player3` anyone who is in the list that joined the channel after the bot was started are not able to play.

**Comment by chrisgillis** [comment]
I'll need to sit down with a few users to debug this one. Looking at the slack client underneath the hood it seems like it will pull the userlist with each call and I dont see any type of caching going on.

**Comment by bboe** [comment]
I should note that the new people had never previously joined the channel, but I don't recall the experience if they leave the channel and rejoin. Thanks for looking into it. We've had some fun with this project.

**Comment by chrisgillis** [comment]
Replication Steps (assuming bot is already in a channel):

* Leave that channel if you are already in it.
* Start the bot
* Join channel
* !start @yourusername

Notes:

RealTimeClient stores a copy of the channel when the bot connects and does not update its userlist as users join / leave the channel. The RealTimeClient class is protected so currently we'll have to extend the class and add some eventing to keep the channel userlist up to date.

**Comment by bboe** [comment]
Awesome. Thanks!
