### ISSUE TITLE
ChannelIdFormatter issue

### ISSUE THREAD

**Issue by ccakes** [chrisgillis/slackwolf#27]
https://github.com/chrisgillis/slackwolf/blob/master/src/Game/Formatter/ChannelIdFormatter.php#L7

How often is a vertical tab (\x0B) returned from the Slack servers in a channel ID? I just set this up and the game channel ID happened to be _CxxxxxGLB_ which was being matched by the trim and dropping the B.

Game seems to play fine with `$trimmed = trim($userId, '<>#\t\n\r');`

I can submit a PR but wanted to see what the story was first

**Comment by chrisgillis** [comment]
I'm pretty sure its safe to remove it, looking at the docs. Not sure why it ended up there in the first place.

**Comment by ThatOneGuyDotNet** [comment]
I believe the actual issue here is that the trim string has to be in double quotes for php to properly escape. I ran into a similiar issue with the UserID formatter and and changing to double quotes (part of https://github.com/chrisgillis/slackwolf/pull/26) fixed the issue.
