### ISSUE TITLE
Add ability to specify role strategy in !start command

### ISSUE THREAD

**Issue by chrisgillis** [chrisgillis/slackwolf#4]

**Comment by chrisgillis** [comment]
This might be better implemented in !setoption?

**Comment by codejr** [comment]
I was looking into doing this but it seems weird have this specified by a global option. Maybe there should be an option for default role strategy but still allow for it to be set in !start.

**Comment by chrisgillis** [comment]
I agree

**Comment by zurbergram** [comment]
Can now do !start chaos or !new vanilla and will create a game with that role strategy
