### ISSUE TITLE
Implement role: Hunter

### ISSUE THREAD

**Issue by chrisgillis** [chrisgillis/slackwolf#6]
The hunter is on the Villager team. When the hunter dies, he may choose another play to die with him.

**Comment by akhyrul** [comment]
Still wrapping my head around the current code. Any pointer where to start?

I'll be happy to contribute for additional roles :+1:

**Comment by chrisgillis** [comment]
This role might be more difficult than others to implement. To get started, I would trace the code from bot.php into gameManager->input() into one of the Command classes. That should get you started.

**Comment by hueyl77** [comment]
Hey @chrisgillis !  Took this weekend to implement the Hunter role.  Check it out when you get a chance?

Pull Request #39

https://github.com/chrisgillis/slackwolf/pull/39
