### ISSUE TITLE
Implement role: Witch

### ISSUE THREAD

**Issue by chrisgillis** [chrisgillis/slackwolf#7]
Witch: Kill or heal a player at night, once each per game. On the Villager team. 

You'll need to modify !kill and create !heal

**Comment by AshleyPinner** [comment]
You might not need to modify `!kill`, witches could use `!poison`

**Comment by hueyl77** [comment]
https://github.com/chrisgillis/slackwolf/pull/29

Anyone wants to help test? :)

https://github.com/hueyl77/slackwolf

Took @AshleyPinner 's suggestion and implemente !poison command.  thanks!
