### ISSUE TITLE
Cannot Start New Game

### ISSUE THREAD

**Issue by chrisgillis** [chrisgillis/slackwolf#70]
I got an e-mail from a team trying to play:

We can not start a game. The log is `Cannot start a game with less than 3 players.`.

We have six people in the slack channel.
What we have done is

*  type in `!new` in `#general` channel, and log is `A new game lobby has been created.  Type !join to play the next game.`
*  make everyone type `!join` in channel
*  tap `!start`, then show the log `Cannot start a game with less than 3 players.`

**Comment by zurbergram** [comment]
Did they run the docker command or pull down the code?

**Comment by chrisgillis** [comment]
Good point. I'll push up a new image and look into setting up a webhook.

**Comment by chrisgillis** [comment]
I pushed up a new docker image, closing unless I hear more about this.
